### ISSUE TITLE
401 'Requires authorization' error from registry on push

### ISSUE THREAD

**Issue by rikkuness** [ekristen/docker-index#31]
From what I can gather the issue is down to the 'Authorization' request header and with the registry logging in debug mode I see the error `check_token: Invalid token format`, looking at the registry code that's thrown as follows:
```python
def _parse_auth_header():
    auth = flask.request.headers.get('authorization', '')
    if auth.split(' ')[0].lower() != 'token':
        logger.debug('check_token: Invalid token format')
```
Looking at the same request in the index logs the authorization header is still showing Basic auth, I assume the registry is expecting `authorization: token <base64>` and instead it is getting `authorization: Basic <base64>`?

The setup is using the nginx reverse proxy and authentication succeeds and authorization appears to work to a degree, attempting to push to a namespace without any permissions indeed returns `"access denied"` as expected, I only get the `"Requires authorization"` error when pushing to a namespace with write permissions for the logged in user.

**Comment by ekristen** [comment]
I need to understand how you have your environment setup before I can help, it sounds like to me it is configured wrong and/or you are talking to the registry when you should be talking to the index and visa versa.

Here is a quick run down. (find me in irc.freenode.net#docker, same username if you want to discuss in real-time)

* Index (index.private.io) (nginx reverse proxied to index:5000)
* Registry (registry.private.io) (nginx reverse proxied registry:5100)

The index is suppose to be configured with env vars that look like this https://github.com/ekristen/docker-index/blob/develop/fig.yml#L23-L28 mind you the TLS env var is there because I'm using self signed certificates within the containers used in the fig setup.

The registry is suppose to be configured to know about the index, like this https://github.com/ekristen/docker-index/blob/develop/fig.yml#L12-L14

If you are using nginx to reverse proxy index.private.io -> index:5000 and registry.private.io -> registry:5100, then nginx should be configured properly.

To login you'd execute `docker login index.private.io`

To tag an image you'd do `docker tag ubuntu index.private.io/test/ubuntu`

To push an image you'd do `docker push index.private.io/test/ubuntu`

No command should ever reference the registry.

How this is works is this ... upon the first initial connection, the docker client/daemon sends your credentials via HTTP Basic Auth to the index, the index then validates them, if everything is ok, it sends a 200. From there the registry will ask if indeed you have permissions and behind the scenes the index generates token authentication that is uses back and forth for each layer you attempt to push.

If your basic auth is going to the registry something is configured incorrectly.

**Comment by rikkuness** [comment]
Tested using 0.9.0 registry, 1.4.0 index and client 1.5+ and still have the issue.

After some searching around I believe this may be down to something mentioned in this thread https://github.com/docker/docker-registry/issues/541#issuecomment-55586491

Could it be my SSL setup that is causing it to keep sending Basic and not token in the auth header?

**Comment by ekristen** [comment]
No your SSL shouldn't have anything to do with it. We've already identified that the index is indeed returning token authentication information. With the registry in full debug mode do you every see token auth sent?

**Comment by rikkuness** [comment]
I see the tokens in there but it also send Basic auth with every request in the 'authorization' header, this is where the registry code is throwing out the 401, it's expecting 'authorization' to be Token, I can't see why the client is sending Basic with every request though. 

I'm using your fig.yml now to start the environment and the only thing I've changed are the CNAME's and I'm mapping my own certificates into /etc/nginx/ssl with a volume.

**Comment by ekristen** [comment]
You have to also map your certificates into the registry container too for that to work.

https://github.com/ekristen/docker-index-registry/blob/master/Dockerfile

I'm running out of ideas :/

**Comment by strima** [comment]
i can confirm the problem and after some investigation (if you can eliminate all other possible issues like ssl, ...) i found that if the client (docker daemon since version 1.4 i assume) does the /v1/_ping and doesn't get the necessary headers X-Docker-Registry-Config and X-Docker-Registry-Standalone (i believe X-Docker-Registry-Standalone is the only relevant one) then he assumes Standalone=true and therefore doesnt send the necessary token.

i modified endpoints/index_defaults.js and added:

    	    res.setHeader('X-Docker-Registry-Config', 'local');
    	    res.setHeader('X-Docker-Registry-Standalone', 'False');

and after that the client started to send the necessary token header

**Comment by rikkuness** [comment]
Did you mean endpoints/index_defaults.js or should that be index/defaults.js? There's no res. defined in the former.

**Comment by ekristen** [comment]
Interesting. Let me take a look. What you says make sense, and that was a bug long ago, I wonder if it somehow got reintroduced. 

I started to rewrite the application so the structure is a little different.

I'll probably take the 1.4.x branch it and push a few more fixes. I don't think I'll ever release version 2 of the index, not with version 2 of the registry coming out and that negates this entire project.

I'm working on my solution for the version 2 registry right now.

**Comment by rikkuness** [comment]
It worked! I can now push!

**Comment by ekristen** [comment]
Fantastic! Apparently a bug in my index :(  We'll see if we can't patch that soon.

**Comment by ekristen** [comment]
I looked more closely at my code @strima @rikkuness this is not a bug. 

https://github.com/ekristen/docker-index/blob/master/index/defaults.js#L16-L30

That makes a call to the registry and passes the results up to the client, so if `config.registry.protocol` is wrong, or it cannot make a successful connection up to the registry, then it will fail.

**Comment by strima** [comment]
@ekristen - well you're right - so the problem (at least for me) was then to use ekristen/docker-index:1.4.0-rc1 (as proposed in the install documentation) - because in there neither in config/default.js nor in config/docker.js is registry.porotocol defined ;)

**Comment by ekristen** [comment]
@strima sorry for the bug, you good to go now?

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
